### ISSUE TITLE
Initial Launch Checklist

### ISSUE THREAD

**Issue by rgbkrk** [noteable-io/platform-site#7]
* [x] Blog Post about Notebooks and LLMs (#1, #10)
* [x] Feature Noteable open source packages on main page (#2)
* [x] Create cell and chat components for use all over the site (#3)
* [x] Google Tag Manager (#5)
* [x] Update CSS and images on main page #9, #12
* [x] ~~Kernel guide docs @robwittman~~
* [x] Prepare GitHub Pages settings #8, #13, #15
* [x] Set DNS for platform.noteable.io to point to our GitHub Pages
